"use client";

/**
 * Language Context (i18n)
 * =======================
 * Multi-language support for the app.
 * Supports: English, Spanish, French, German, Arabic, Japanese, Korean, Chinese
 */

import { createContext, useContext, useState, useEffect, useCallback, type ReactNode } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'de' | 'ar' | 'ja' | 'ko' | 'zh';

export const LANGUAGES: { code: Language; name: string; nativeName: string; flag: string; rtl?: boolean }[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦', rtl: true },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
];

// Translation keys
type TranslationKey = keyof typeof translations.en;

// Translations
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.discover': 'Discover',
    'nav.ai': 'AI Search',
    'nav.library': 'Library',
    'nav.profile': 'Profile',
    'nav.search': 'Search movies...',
    'nav.movieNight': 'Movie Night',
    
    // Home
    'home.trending': 'Trending This Week',
    'home.nowPlaying': 'Now Playing',
    'home.upcoming': 'Coming Soon',
    'home.watchNow': 'Watch Now',
    'home.addToWatchlist': 'Add to Watchlist',
    
    // Movie Details
    'movie.director': 'Director',
    'movie.cast': 'Cast',
    'movie.overview': 'Overview',
    'movie.similar': 'Similar Movies',
    'movie.runtime': 'Runtime',
    'movie.rating': 'Rating',
    'movie.releaseDate': 'Release Date',
    'movie.addToWatchlist': 'Add to Watchlist',
    'movie.removeFromWatchlist': 'Remove from Watchlist',
    'movie.addToFavorites': 'Add to Favorites',
    'movie.removeFromFavorites': 'Remove from Favorites',
    'movie.watchTrailer': 'Watch Trailer',
    'movie.whereToWatch': 'Where to Watch',
    'movie.stream': 'Stream',
    'movie.rent': 'Rent',
    'movie.buy': 'Buy',
    'movie.soundtrack': 'Soundtrack',
    'movie.addToCalendar': 'Add to Calendar',
    
    // Library
    'library.title': 'My Library',
    'library.subtitle': 'Your personal movie collection, all in one place',
    'library.watchlist': 'Watchlist',
    'library.favorites': 'Favorites',
    'library.collections': 'Collections',
    'library.ratings': 'My Ratings',
    'library.history': 'History',
    'library.stats': 'Stats',
    'library.achievements': 'Achievements',
    'library.compare': 'Compare',
    'library.export': 'Export Data',
    'library.import': 'Import Data',
    'library.empty': 'No movies yet',
    'library.emptySubtitle': 'Start adding movies to your collection!',
    
    // Discover
    'discover.title': 'Discover',
    'discover.randomPicker': 'Random Movie Picker',
    'discover.moodBased': 'Mood-Based Discovery',
    'discover.spin': 'Spin the Wheel',
    'discover.howFeeling': 'How are you feeling?',
    
    // AI Search
    'ai.title': 'AI Movie Search',
    'ai.placeholder': 'Ask me anything about movies...',
    'ai.thinking': 'Thinking...',
    'ai.suggestions': 'Try asking:',
    
    // Profile
    'profile.title': 'Your Profile',
    'profile.signIn': 'Sign In',
    'profile.signOut': 'Sign Out',
    'profile.settings': 'Settings',
    'profile.theme': 'Theme',
    'profile.language': 'Language',
    'profile.darkMode': 'Dark Mode',
    'profile.lightMode': 'Light Mode',
    'profile.systemTheme': 'System',
    'profile.syncStatus': 'Cloud Sync',
    'profile.lastSync': 'Last synced',
    
    // Watch Party
    'party.title': 'Watch Parties',
    'party.create': 'Create Watch Party',
    'party.share': 'Share Party',
    'party.import': 'Import Party',
    'party.empty': 'No watch parties yet',
    
    // Movie Night
    'movieNight.title': 'Movie Night',
    'movieNight.subtitle': 'Decide what to watch together',
    'movieNight.swipeMode': 'Swipe Mode',
    'movieNight.voteMode': 'Group Vote',
    'movieNight.timerMode': 'Decision Timer',
    'movieNight.swipeLeft': 'Not tonight',
    'movieNight.swipeRight': 'Let\'s watch!',
    'movieNight.vote': 'Vote',
    'movieNight.startTimer': 'Start Timer',
    'movieNight.timeUp': 'Time\'s up!',
    'movieNight.winner': 'Tonight\'s pick:',
    'movieNight.addMovies': 'Add movies to decide',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Something went wrong',
    'common.retry': 'Try Again',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.share': 'Share',
    'common.copy': 'Copy',
    'common.copied': 'Copied!',
    'common.minutes': 'min',
    'common.hours': 'hr',
    'common.today': 'Today',
    'common.yesterday': 'Yesterday',
    'common.movies': 'movies',
    'common.noResults': 'No results found',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.discover': 'Descubrir',
    'nav.ai': 'Búsqueda IA',
    'nav.library': 'Biblioteca',
    'nav.profile': 'Perfil',
    'nav.search': 'Buscar películas...',
    'nav.movieNight': 'Noche de Cine',
    'home.trending': 'Tendencias Esta Semana',
    'home.nowPlaying': 'En Cartelera',
    'home.upcoming': 'Próximamente',
    'home.watchNow': 'Ver Ahora',
    'home.addToWatchlist': 'Añadir a Lista',
    'movie.director': 'Director',
    'movie.cast': 'Reparto',
    'movie.overview': 'Sinopsis',
    'movie.similar': 'Películas Similares',
    'movie.runtime': 'Duración',
    'movie.rating': 'Puntuación',
    'movie.releaseDate': 'Fecha de Estreno',
    'movie.addToWatchlist': 'Añadir a Lista',
    'movie.removeFromWatchlist': 'Quitar de Lista',
    'movie.addToFavorites': 'Añadir a Favoritos',
    'movie.removeFromFavorites': 'Quitar de Favoritos',
    'movie.watchTrailer': 'Ver Tráiler',
    'movie.whereToWatch': 'Dónde Ver',
    'movie.stream': 'Streaming',
    'movie.rent': 'Alquilar',
    'movie.buy': 'Comprar',
    'movie.soundtrack': 'Banda Sonora',
    'movie.addToCalendar': 'Añadir al Calendario',
    'library.title': 'Mi Biblioteca',
    'library.subtitle': 'Tu colección personal de películas',
    'library.watchlist': 'Lista de Seguimiento',
    'library.favorites': 'Favoritos',
    'library.collections': 'Colecciones',
    'library.ratings': 'Mis Puntuaciones',
    'library.history': 'Historial',
    'library.stats': 'Estadísticas',
    'library.achievements': 'Logros',
    'library.compare': 'Comparar',
    'library.export': 'Exportar Datos',
    'library.import': 'Importar Datos',
    'library.empty': 'Sin películas aún',
    'library.emptySubtitle': '¡Empieza a añadir películas!',
    'discover.title': 'Descubrir',
    'discover.randomPicker': 'Selector Aleatorio',
    'discover.moodBased': 'Por Estado de Ánimo',
    'discover.spin': 'Girar la Ruleta',
    'discover.howFeeling': '¿Cómo te sientes?',
    'ai.title': 'Búsqueda IA',
    'ai.placeholder': 'Pregúntame sobre películas...',
    'ai.thinking': 'Pensando...',
    'ai.suggestions': 'Prueba preguntar:',
    'profile.title': 'Tu Perfil',
    'profile.signIn': 'Iniciar Sesión',
    'profile.signOut': 'Cerrar Sesión',
    'profile.settings': 'Configuración',
    'profile.theme': 'Tema',
    'profile.language': 'Idioma',
    'profile.darkMode': 'Modo Oscuro',
    'profile.lightMode': 'Modo Claro',
    'profile.systemTheme': 'Sistema',
    'profile.syncStatus': 'Sincronización',
    'profile.lastSync': 'Última sincronización',
    'party.title': 'Fiestas de Cine',
    'party.create': 'Crear Fiesta',
    'party.share': 'Compartir',
    'party.import': 'Importar',
    'party.empty': 'Sin fiestas aún',
    'movieNight.title': 'Noche de Cine',
    'movieNight.subtitle': 'Decide qué ver juntos',
    'movieNight.swipeMode': 'Modo Deslizar',
    'movieNight.voteMode': 'Votación Grupal',
    'movieNight.timerMode': 'Temporizador',
    'movieNight.swipeLeft': 'Esta noche no',
    'movieNight.swipeRight': '¡Veámosla!',
    'movieNight.vote': 'Votar',
    'movieNight.startTimer': 'Iniciar Temporizador',
    'movieNight.timeUp': '¡Tiempo!',
    'movieNight.winner': 'La elección de esta noche:',
    'movieNight.addMovies': 'Añade películas para decidir',
    'common.loading': 'Cargando...',
    'common.error': 'Algo salió mal',
    'common.retry': 'Reintentar',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.share': 'Compartir',
    'common.copy': 'Copiar',
    'common.copied': '¡Copiado!',
    'common.minutes': 'min',
    'common.hours': 'hr',
    'common.today': 'Hoy',
    'common.yesterday': 'Ayer',
    'common.movies': 'películas',
    'common.noResults': 'Sin resultados',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.discover': 'Découvrir',
    'nav.ai': 'Recherche IA',
    'nav.library': 'Bibliothèque',
    'nav.profile': 'Profil',
    'nav.search': 'Rechercher des films...',
    'nav.movieNight': 'Soirée Ciné',
    'home.trending': 'Tendances Cette Semaine',
    'home.nowPlaying': 'À l\'Affiche',
    'home.upcoming': 'Prochainement',
    'home.watchNow': 'Regarder',
    'home.addToWatchlist': 'Ajouter à la Liste',
    'movie.director': 'Réalisateur',
    'movie.cast': 'Distribution',
    'movie.overview': 'Synopsis',
    'movie.similar': 'Films Similaires',
    'movie.runtime': 'Durée',
    'movie.rating': 'Note',
    'movie.releaseDate': 'Date de Sortie',
    'movie.addToWatchlist': 'Ajouter à la Liste',
    'movie.removeFromWatchlist': 'Retirer de la Liste',
    'movie.addToFavorites': 'Ajouter aux Favoris',
    'movie.removeFromFavorites': 'Retirer des Favoris',
    'movie.watchTrailer': 'Voir la Bande-Annonce',
    'movie.whereToWatch': 'Où Regarder',
    'movie.stream': 'Streaming',
    'movie.rent': 'Louer',
    'movie.buy': 'Acheter',
    'movie.soundtrack': 'Bande Originale',
    'movie.addToCalendar': 'Ajouter au Calendrier',
    'library.title': 'Ma Bibliothèque',
    'library.subtitle': 'Votre collection personnelle de films',
    'library.watchlist': 'À Voir',
    'library.favorites': 'Favoris',
    'library.collections': 'Collections',
    'library.ratings': 'Mes Notes',
    'library.history': 'Historique',
    'library.stats': 'Statistiques',
    'library.achievements': 'Succès',
    'library.compare': 'Comparer',
    'library.export': 'Exporter',
    'library.import': 'Importer',
    'library.empty': 'Aucun film',
    'library.emptySubtitle': 'Commencez à ajouter des films!',
    'discover.title': 'Découvrir',
    'discover.randomPicker': 'Sélection Aléatoire',
    'discover.moodBased': 'Par Humeur',
    'discover.spin': 'Tourner la Roue',
    'discover.howFeeling': 'Comment vous sentez-vous?',
    'ai.title': 'Recherche IA',
    'ai.placeholder': 'Posez-moi des questions sur les films...',
    'ai.thinking': 'Réflexion...',
    'ai.suggestions': 'Essayez de demander:',
    'profile.title': 'Votre Profil',
    'profile.signIn': 'Connexion',
    'profile.signOut': 'Déconnexion',
    'profile.settings': 'Paramètres',
    'profile.theme': 'Thème',
    'profile.language': 'Langue',
    'profile.darkMode': 'Mode Sombre',
    'profile.lightMode': 'Mode Clair',
    'profile.systemTheme': 'Système',
    'profile.syncStatus': 'Synchronisation',
    'profile.lastSync': 'Dernière sync',
    'party.title': 'Soirées Ciné',
    'party.create': 'Créer une Soirée',
    'party.share': 'Partager',
    'party.import': 'Importer',
    'party.empty': 'Aucune soirée',
    'movieNight.title': 'Soirée Ciné',
    'movieNight.subtitle': 'Décidez quoi regarder ensemble',
    'movieNight.swipeMode': 'Mode Swipe',
    'movieNight.voteMode': 'Vote de Groupe',
    'movieNight.timerMode': 'Minuterie',
    'movieNight.swipeLeft': 'Pas ce soir',
    'movieNight.swipeRight': 'On regarde!',
    'movieNight.vote': 'Voter',
    'movieNight.startTimer': 'Démarrer',
    'movieNight.timeUp': 'Temps écoulé!',
    'movieNight.winner': 'Le choix de ce soir:',
    'movieNight.addMovies': 'Ajoutez des films',
    'common.loading': 'Chargement...',
    'common.error': 'Une erreur est survenue',
    'common.retry': 'Réessayer',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.share': 'Partager',
    'common.copy': 'Copier',
    'common.copied': 'Copié!',
    'common.minutes': 'min',
    'common.hours': 'h',
    'common.today': 'Aujourd\'hui',
    'common.yesterday': 'Hier',
    'common.movies': 'films',
    'common.noResults': 'Aucun résultat',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.discover': 'Entdecken',
    'nav.ai': 'KI-Suche',
    'nav.library': 'Bibliothek',
    'nav.profile': 'Profil',
    'nav.search': 'Filme suchen...',
    'nav.movieNight': 'Filmabend',
    'home.trending': 'Trending Diese Woche',
    'home.nowPlaying': 'Jetzt im Kino',
    'home.upcoming': 'Demnächst',
    'home.watchNow': 'Jetzt Ansehen',
    'home.addToWatchlist': 'Zur Watchlist',
    'movie.director': 'Regie',
    'movie.cast': 'Besetzung',
    'movie.overview': 'Handlung',
    'movie.similar': 'Ähnliche Filme',
    'movie.runtime': 'Laufzeit',
    'movie.rating': 'Bewertung',
    'movie.releaseDate': 'Erscheinungsdatum',
    'movie.addToWatchlist': 'Zur Watchlist',
    'movie.removeFromWatchlist': 'Von Watchlist entfernen',
    'movie.addToFavorites': 'Zu Favoriten',
    'movie.removeFromFavorites': 'Von Favoriten entfernen',
    'movie.watchTrailer': 'Trailer Ansehen',
    'movie.whereToWatch': 'Wo Ansehen',
    'movie.stream': 'Streamen',
    'movie.rent': 'Leihen',
    'movie.buy': 'Kaufen',
    'movie.soundtrack': 'Soundtrack',
    'movie.addToCalendar': 'Zum Kalender',
    'library.title': 'Meine Bibliothek',
    'library.subtitle': 'Deine persönliche Filmsammlung',
    'library.watchlist': 'Watchlist',
    'library.favorites': 'Favoriten',
    'library.collections': 'Sammlungen',
    'library.ratings': 'Meine Bewertungen',
    'library.history': 'Verlauf',
    'library.stats': 'Statistiken',
    'library.achievements': 'Erfolge',
    'library.compare': 'Vergleichen',
    'library.export': 'Exportieren',
    'library.import': 'Importieren',
    'library.empty': 'Noch keine Filme',
    'library.emptySubtitle': 'Beginne Filme hinzuzufügen!',
    'discover.title': 'Entdecken',
    'discover.randomPicker': 'Zufallsauswahl',
    'discover.moodBased': 'Nach Stimmung',
    'discover.spin': 'Rad Drehen',
    'discover.howFeeling': 'Wie fühlst du dich?',
    'ai.title': 'KI-Filmsuche',
    'ai.placeholder': 'Frag mich etwas über Filme...',
    'ai.thinking': 'Denke nach...',
    'ai.suggestions': 'Probiere:',
    'profile.title': 'Dein Profil',
    'profile.signIn': 'Anmelden',
    'profile.signOut': 'Abmelden',
    'profile.settings': 'Einstellungen',
    'profile.theme': 'Design',
    'profile.language': 'Sprache',
    'profile.darkMode': 'Dunkel',
    'profile.lightMode': 'Hell',
    'profile.systemTheme': 'System',
    'profile.syncStatus': 'Cloud-Sync',
    'profile.lastSync': 'Zuletzt synchronisiert',
    'party.title': 'Filmpartys',
    'party.create': 'Party Erstellen',
    'party.share': 'Teilen',
    'party.import': 'Importieren',
    'party.empty': 'Keine Partys',
    'movieNight.title': 'Filmabend',
    'movieNight.subtitle': 'Entscheidet gemeinsam',
    'movieNight.swipeMode': 'Swipe-Modus',
    'movieNight.voteMode': 'Gruppenabstimmung',
    'movieNight.timerMode': 'Timer',
    'movieNight.swipeLeft': 'Heute nicht',
    'movieNight.swipeRight': 'Schauen wir!',
    'movieNight.vote': 'Abstimmen',
    'movieNight.startTimer': 'Timer Starten',
    'movieNight.timeUp': 'Zeit ist um!',
    'movieNight.winner': 'Heutige Wahl:',
    'movieNight.addMovies': 'Filme hinzufügen',
    'common.loading': 'Laden...',
    'common.error': 'Etwas ist schiefgelaufen',
    'common.retry': 'Erneut versuchen',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.share': 'Teilen',
    'common.copy': 'Kopieren',
    'common.copied': 'Kopiert!',
    'common.minutes': 'Min',
    'common.hours': 'Std',
    'common.today': 'Heute',
    'common.yesterday': 'Gestern',
    'common.movies': 'Filme',
    'common.noResults': 'Keine Ergebnisse',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.discover': 'اكتشف',
    'nav.ai': 'بحث ذكي',
    'nav.library': 'مكتبتي',
    'nav.profile': 'الملف الشخصي',
    'nav.search': 'ابحث عن أفلام...',
    'nav.movieNight': 'ليلة الفيلم',
    'home.trending': 'الرائج هذا الأسبوع',
    'home.nowPlaying': 'يعرض الآن',
    'home.upcoming': 'قريباً',
    'home.watchNow': 'شاهد الآن',
    'home.addToWatchlist': 'أضف للقائمة',
    'movie.director': 'المخرج',
    'movie.cast': 'طاقم التمثيل',
    'movie.overview': 'القصة',
    'movie.similar': 'أفلام مشابهة',
    'movie.runtime': 'المدة',
    'movie.rating': 'التقييم',
    'movie.releaseDate': 'تاريخ الإصدار',
    'movie.addToWatchlist': 'أضف للقائمة',
    'movie.removeFromWatchlist': 'إزالة من القائمة',
    'movie.addToFavorites': 'أضف للمفضلة',
    'movie.removeFromFavorites': 'إزالة من المفضلة',
    'movie.watchTrailer': 'شاهد الإعلان',
    'movie.whereToWatch': 'أين تشاهد',
    'movie.stream': 'بث مباشر',
    'movie.rent': 'استئجار',
    'movie.buy': 'شراء',
    'movie.soundtrack': 'الموسيقى',
    'movie.addToCalendar': 'أضف للتقويم',
    'library.title': 'مكتبتي',
    'library.subtitle': 'مجموعتك الشخصية من الأفلام',
    'library.watchlist': 'قائمة المشاهدة',
    'library.favorites': 'المفضلة',
    'library.collections': 'المجموعات',
    'library.ratings': 'تقييماتي',
    'library.history': 'السجل',
    'library.stats': 'الإحصائيات',
    'library.achievements': 'الإنجازات',
    'library.compare': 'مقارنة',
    'library.export': 'تصدير',
    'library.import': 'استيراد',
    'library.empty': 'لا توجد أفلام',
    'library.emptySubtitle': 'ابدأ بإضافة الأفلام!',
    'discover.title': 'اكتشف',
    'discover.randomPicker': 'اختيار عشوائي',
    'discover.moodBased': 'حسب المزاج',
    'discover.spin': 'أدر العجلة',
    'discover.howFeeling': 'كيف تشعر؟',
    'ai.title': 'البحث الذكي',
    'ai.placeholder': 'اسألني عن الأفلام...',
    'ai.thinking': 'جاري التفكير...',
    'ai.suggestions': 'جرب السؤال:',
    'profile.title': 'ملفك الشخصي',
    'profile.signIn': 'تسجيل الدخول',
    'profile.signOut': 'تسجيل الخروج',
    'profile.settings': 'الإعدادات',
    'profile.theme': 'المظهر',
    'profile.language': 'اللغة',
    'profile.darkMode': 'داكن',
    'profile.lightMode': 'فاتح',
    'profile.systemTheme': 'النظام',
    'profile.syncStatus': 'المزامنة',
    'profile.lastSync': 'آخر مزامنة',
    'party.title': 'حفلات الأفلام',
    'party.create': 'إنشاء حفلة',
    'party.share': 'مشاركة',
    'party.import': 'استيراد',
    'party.empty': 'لا توجد حفلات',
    'movieNight.title': 'ليلة الفيلم',
    'movieNight.subtitle': 'قرروا معاً ماذا تشاهدون',
    'movieNight.swipeMode': 'وضع السحب',
    'movieNight.voteMode': 'تصويت جماعي',
    'movieNight.timerMode': 'مؤقت',
    'movieNight.swipeLeft': 'ليس الليلة',
    'movieNight.swipeRight': 'لنشاهده!',
    'movieNight.vote': 'صوّت',
    'movieNight.startTimer': 'ابدأ المؤقت',
    'movieNight.timeUp': 'انتهى الوقت!',
    'movieNight.winner': 'اختيار الليلة:',
    'movieNight.addMovies': 'أضف أفلاماً للاختيار',
    'common.loading': 'جاري التحميل...',
    'common.error': 'حدث خطأ',
    'common.retry': 'إعادة المحاولة',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.share': 'مشاركة',
    'common.copy': 'نسخ',
    'common.copied': 'تم النسخ!',
    'common.minutes': 'دقيقة',
    'common.hours': 'ساعة',
    'common.today': 'اليوم',
    'common.yesterday': 'أمس',
    'common.movies': 'أفلام',
    'common.noResults': 'لا توجد نتائج',
  },
  ja: {
    'nav.home': 'ホーム',
    'nav.discover': '探索',
    'nav.ai': 'AI検索',
    'nav.library': 'ライブラリ',
    'nav.profile': 'プロフィール',
    'nav.search': '映画を検索...',
    'nav.movieNight': '映画ナイト',
    'home.trending': '今週のトレンド',
    'home.nowPlaying': '上映中',
    'home.upcoming': '近日公開',
    'home.watchNow': '今すぐ視聴',
    'home.addToWatchlist': 'ウォッチリストに追加',
    'movie.director': '監督',
    'movie.cast': 'キャスト',
    'movie.overview': 'あらすじ',
    'movie.similar': '類似作品',
    'movie.runtime': '上映時間',
    'movie.rating': '評価',
    'movie.releaseDate': '公開日',
    'movie.addToWatchlist': 'ウォッチリストに追加',
    'movie.removeFromWatchlist': 'ウォッチリストから削除',
    'movie.addToFavorites': 'お気に入りに追加',
    'movie.removeFromFavorites': 'お気に入りから削除',
    'movie.watchTrailer': '予告編を見る',
    'movie.whereToWatch': '視聴可能なサービス',
    'movie.stream': 'ストリーミング',
    'movie.rent': 'レンタル',
    'movie.buy': '購入',
    'movie.soundtrack': 'サウンドトラック',
    'movie.addToCalendar': 'カレンダーに追加',
    'library.title': 'マイライブラリ',
    'library.subtitle': 'あなたの映画コレクション',
    'library.watchlist': 'ウォッチリスト',
    'library.favorites': 'お気に入り',
    'library.collections': 'コレクション',
    'library.ratings': 'マイ評価',
    'library.history': '履歴',
    'library.stats': '統計',
    'library.achievements': '実績',
    'library.compare': '比較',
    'library.export': 'エクスポート',
    'library.import': 'インポート',
    'library.empty': '映画がありません',
    'library.emptySubtitle': '映画を追加しましょう！',
    'discover.title': '探索',
    'discover.randomPicker': 'ランダム選択',
    'discover.moodBased': '気分で選ぶ',
    'discover.spin': 'ルーレットを回す',
    'discover.howFeeling': '今の気分は？',
    'ai.title': 'AI映画検索',
    'ai.placeholder': '映画について何でも聞いてください...',
    'ai.thinking': '考え中...',
    'ai.suggestions': '例えば:',
    'profile.title': 'プロフィール',
    'profile.signIn': 'サインイン',
    'profile.signOut': 'サインアウト',
    'profile.settings': '設定',
    'profile.theme': 'テーマ',
    'profile.language': '言語',
    'profile.darkMode': 'ダーク',
    'profile.lightMode': 'ライト',
    'profile.systemTheme': 'システム',
    'profile.syncStatus': 'クラウド同期',
    'profile.lastSync': '最終同期',
    'party.title': 'ウォッチパーティー',
    'party.create': 'パーティー作成',
    'party.share': '共有',
    'party.import': 'インポート',
    'party.empty': 'パーティーなし',
    'movieNight.title': '映画ナイト',
    'movieNight.subtitle': 'みんなで決めよう',
    'movieNight.swipeMode': 'スワイプモード',
    'movieNight.voteMode': 'グループ投票',
    'movieNight.timerMode': 'タイマー',
    'movieNight.swipeLeft': '今日はパス',
    'movieNight.swipeRight': '見よう！',
    'movieNight.vote': '投票',
    'movieNight.startTimer': 'タイマー開始',
    'movieNight.timeUp': '時間切れ！',
    'movieNight.winner': '今夜の選択:',
    'movieNight.addMovies': '映画を追加してください',
    'common.loading': '読み込み中...',
    'common.error': 'エラーが発生しました',
    'common.retry': '再試行',
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.delete': '削除',
    'common.edit': '編集',
    'common.share': '共有',
    'common.copy': 'コピー',
    'common.copied': 'コピーしました！',
    'common.minutes': '分',
    'common.hours': '時間',
    'common.today': '今日',
    'common.yesterday': '昨日',
    'common.movies': '本',
    'common.noResults': '結果なし',
  },
  ko: {
    'nav.home': '홈',
    'nav.discover': '탐색',
    'nav.ai': 'AI 검색',
    'nav.library': '라이브러리',
    'nav.profile': '프로필',
    'nav.search': '영화 검색...',
    'nav.movieNight': '무비 나이트',
    'home.trending': '이번 주 인기',
    'home.nowPlaying': '현재 상영중',
    'home.upcoming': '개봉 예정',
    'home.watchNow': '지금 보기',
    'home.addToWatchlist': '보고싶어요',
    'movie.director': '감독',
    'movie.cast': '출연',
    'movie.overview': '줄거리',
    'movie.similar': '비슷한 영화',
    'movie.runtime': '상영시간',
    'movie.rating': '평점',
    'movie.releaseDate': '개봉일',
    'movie.addToWatchlist': '보고싶어요',
    'movie.removeFromWatchlist': '보고싶어요 취소',
    'movie.addToFavorites': '좋아요',
    'movie.removeFromFavorites': '좋아요 취소',
    'movie.watchTrailer': '예고편 보기',
    'movie.whereToWatch': '시청 가능한 곳',
    'movie.stream': '스트리밍',
    'movie.rent': '대여',
    'movie.buy': '구매',
    'movie.soundtrack': '사운드트랙',
    'movie.addToCalendar': '캘린더에 추가',
    'library.title': '내 라이브러리',
    'library.subtitle': '나만의 영화 컬렉션',
    'library.watchlist': '보고싶어요',
    'library.favorites': '좋아요',
    'library.collections': '컬렉션',
    'library.ratings': '내 평점',
    'library.history': '시청 기록',
    'library.stats': '통계',
    'library.achievements': '업적',
    'library.compare': '비교',
    'library.export': '내보내기',
    'library.import': '가져오기',
    'library.empty': '영화가 없습니다',
    'library.emptySubtitle': '영화를 추가해보세요!',
    'discover.title': '탐색',
    'discover.randomPicker': '랜덤 선택',
    'discover.moodBased': '기분별 추천',
    'discover.spin': '룰렛 돌리기',
    'discover.howFeeling': '오늘 기분이 어때요?',
    'ai.title': 'AI 영화 검색',
    'ai.placeholder': '영화에 대해 물어보세요...',
    'ai.thinking': '생각 중...',
    'ai.suggestions': '이렇게 물어보세요:',
    'profile.title': '프로필',
    'profile.signIn': '로그인',
    'profile.signOut': '로그아웃',
    'profile.settings': '설정',
    'profile.theme': '테마',
    'profile.language': '언어',
    'profile.darkMode': '다크 모드',
    'profile.lightMode': '라이트 모드',
    'profile.systemTheme': '시스템',
    'profile.syncStatus': '클라우드 동기화',
    'profile.lastSync': '마지막 동기화',
    'party.title': '워치 파티',
    'party.create': '파티 만들기',
    'party.share': '공유',
    'party.import': '가져오기',
    'party.empty': '파티가 없습니다',
    'movieNight.title': '무비 나이트',
    'movieNight.subtitle': '함께 결정하세요',
    'movieNight.swipeMode': '스와이프 모드',
    'movieNight.voteMode': '그룹 투표',
    'movieNight.timerMode': '타이머',
    'movieNight.swipeLeft': '오늘은 패스',
    'movieNight.swipeRight': '보자!',
    'movieNight.vote': '투표',
    'movieNight.startTimer': '타이머 시작',
    'movieNight.timeUp': '시간 종료!',
    'movieNight.winner': '오늘의 선택:',
    'movieNight.addMovies': '영화를 추가하세요',
    'common.loading': '로딩 중...',
    'common.error': '오류가 발생했습니다',
    'common.retry': '다시 시도',
    'common.save': '저장',
    'common.cancel': '취소',
    'common.delete': '삭제',
    'common.edit': '편집',
    'common.share': '공유',
    'common.copy': '복사',
    'common.copied': '복사됨!',
    'common.minutes': '분',
    'common.hours': '시간',
    'common.today': '오늘',
    'common.yesterday': '어제',
    'common.movies': '편',
    'common.noResults': '결과 없음',
  },
  zh: {
    'nav.home': '首页',
    'nav.discover': '发现',
    'nav.ai': 'AI搜索',
    'nav.library': '片库',
    'nav.profile': '个人中心',
    'nav.search': '搜索电影...',
    'nav.movieNight': '电影之夜',
    'home.trending': '本周热门',
    'home.nowPlaying': '正在热映',
    'home.upcoming': '即将上映',
    'home.watchNow': '立即观看',
    'home.addToWatchlist': '想看',
    'movie.director': '导演',
    'movie.cast': '演员',
    'movie.overview': '剧情简介',
    'movie.similar': '相似电影',
    'movie.runtime': '时长',
    'movie.rating': '评分',
    'movie.releaseDate': '上映日期',
    'movie.addToWatchlist': '想看',
    'movie.removeFromWatchlist': '取消想看',
    'movie.addToFavorites': '收藏',
    'movie.removeFromFavorites': '取消收藏',
    'movie.watchTrailer': '观看预告片',
    'movie.whereToWatch': '在哪观看',
    'movie.stream': '流媒体',
    'movie.rent': '租借',
    'movie.buy': '购买',
    'movie.soundtrack': '原声带',
    'movie.addToCalendar': '添加到日历',
    'library.title': '我的片库',
    'library.subtitle': '你的个人电影收藏',
    'library.watchlist': '想看',
    'library.favorites': '收藏',
    'library.collections': '片单',
    'library.ratings': '我的评分',
    'library.history': '观影历史',
    'library.stats': '统计',
    'library.achievements': '成就',
    'library.compare': '对比',
    'library.export': '导出数据',
    'library.import': '导入数据',
    'library.empty': '暂无电影',
    'library.emptySubtitle': '开始添加电影吧！',
    'discover.title': '发现',
    'discover.randomPicker': '随机选片',
    'discover.moodBased': '按心情推荐',
    'discover.spin': '转动转盘',
    'discover.howFeeling': '你现在心情如何？',
    'ai.title': 'AI电影搜索',
    'ai.placeholder': '问我任何关于电影的问题...',
    'ai.thinking': '思考中...',
    'ai.suggestions': '试试这样问:',
    'profile.title': '个人中心',
    'profile.signIn': '登录',
    'profile.signOut': '退出登录',
    'profile.settings': '设置',
    'profile.theme': '主题',
    'profile.language': '语言',
    'profile.darkMode': '深色模式',
    'profile.lightMode': '浅色模式',
    'profile.systemTheme': '跟随系统',
    'profile.syncStatus': '云同步',
    'profile.lastSync': '上次同步',
    'party.title': '观影派对',
    'party.create': '创建派对',
    'party.share': '分享',
    'party.import': '导入',
    'party.empty': '暂无派对',
    'movieNight.title': '电影之夜',
    'movieNight.subtitle': '一起决定看什么',
    'movieNight.swipeMode': '滑动模式',
    'movieNight.voteMode': '群组投票',
    'movieNight.timerMode': '倒计时',
    'movieNight.swipeLeft': '今晚不看',
    'movieNight.swipeRight': '就它了！',
    'movieNight.vote': '投票',
    'movieNight.startTimer': '开始计时',
    'movieNight.timeUp': '时间到！',
    'movieNight.winner': '今晚的选择:',
    'movieNight.addMovies': '添加电影来决定',
    'common.loading': '加载中...',
    'common.error': '出错了',
    'common.retry': '重试',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.share': '分享',
    'common.copy': '复制',
    'common.copied': '已复制！',
    'common.minutes': '分钟',
    'common.hours': '小时',
    'common.today': '今天',
    'common.yesterday': '昨天',
    'common.movies': '部电影',
    'common.noResults': '无结果',
  },
} as const;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

const LANG_STORAGE_KEY = 'scanmovie_language';

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  // Initialize from localStorage or browser language
  useEffect(() => {
    const stored = localStorage.getItem(LANG_STORAGE_KEY) as Language | null;
    if (stored && Object.keys(translations).includes(stored)) {
      setLanguageState(stored);
    } else {
      // Try to detect from browser
      const browserLang = navigator.language.split('-')[0] as Language;
      if (Object.keys(translations).includes(browserLang)) {
        setLanguageState(browserLang);
      }
    }
  }, []);

  // Apply RTL direction if needed
  useEffect(() => {
    const langInfo = LANGUAGES.find(l => l.code === language);
    document.documentElement.dir = langInfo?.rtl ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(LANG_STORAGE_KEY, lang);
  }, []);

  const t = useCallback((key: TranslationKey): string => {
    const langTranslations = translations[language];
    return (langTranslations as any)[key] || translations.en[key] || key;
  }, [language]);

  const isRTL = LANGUAGES.find(l => l.code === language)?.rtl || false;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
